title: "SRE Laptop Restore Runbook"
description: "Documentation for Javier Lozadaâ€™s full SRE laptop backup and restore environment."
theme: "just-the-docs"

search_enabled: true

markdown: kramdown
kramdown:
  input: GFM
