title: "SRE Laptop Restore Runbook"
description: "Documentation for restoring and maintaining Javier Lozadaâ€™s SRE laptop environment."

remote_theme: just-the-docs/just-the-docs

search_enabled: true

markdown: kramdown
kramdown:
  input: GFM

just_the_docs:
  mermaid:
    enabled: true
